CREATE TABLE IF NOT EXISTS games (
  id VARCHAR(24) PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  edit_token_hash VARCHAR(255) NOT NULL,
  state_json LONGTEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  locked TINYINT(1) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS game_audit_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  game_id VARCHAR(24) NOT NULL,
  action VARCHAR(40) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);

