on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Autodeployment Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /var/www/html/golfbangers.my.id
            git config --global --add safe.directory /var/www/html/golfbangers.my.id
            git fetch origin
            git checkout main
            git pull origin main
            chown -R www-data:www-data /var/www/html/golfbangers.my.id
            chown -R root:root /var/www/html/golfbangers.my.id/.git
            git rev-parse --short HEAD
